// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Infrastructure.Implementations.ExecuteAndCatchErrorsMicrostation.ExecuteAndHandleError(System.Action,System.Action,System.Action,GadzhiMicrostation.Models.Implementations.ErrorMicrostation,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.DependencyInjection.BootStrapMicrostation.BootStrapUnityMicrostation.Start(Microsoft.Practices.Unity.IUnityContainer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Infrastructure.Implementations.PdfCreatorService.PrintPDF(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Infrastructure.Implementations.ExecuteAndCatchErrorsMicrostation.ExecuteAndHandleError(System.Action,System.Action,System.Action,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Infrastructure.Implementations.ExecuteAndCatchErrorsMicrostation.ExecuteAndHandleError(System.Action,System.Action,System.Func{GadzhiMicrostation.Models.Enums.ErrorMicrostationType},System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Infrastructure.Implementations.ExecuteAndCatchErrorsMicrostation.ExecuteAndHandleError(System.Action,System.Action,System.Func{GadzhiMicrostation.Models.Implementations.ErrorMicrostation},System.Action)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Microstation.Implementations.ApplicationMicrostationPartial.ApplicationMicrostation.PrintStamp(GadzhiApplicationCommon.Models.Interfaces.StampCollections.IStamp,GadzhiMicrostation.Models.Enums.ColorPrintApplication,System.String)~GadzhiApplicationCommon.Models.Interfaces.IResultApplication")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Extensions.StringAdditional.StringAdditionalExtensions.FirstCharToUpper(System.String)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiMicrostation.Extensions.StringAdditional.StringAdditionalExtensions.FirstCharToLower(System.String)~System.String")]
