// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Action,System.Action)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleError(System.Action,System.Action,System.Action,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.FileSystemOperations.ConvertFileToByteAndZip(System.String)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleError(System.Action,System.Action,System.Func{GadzhiCommon.Models.Interfaces.Errors.IErrorConverting},System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Func{GadzhiCommon.Models.Interfaces.Errors.IErrorConverting},System.Action)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Func{System.Threading.Tasks.Task{GadzhiCommon.Models.Interfaces.Errors.IErrorConverting}},System.Action)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Action,System.Action)~System.Threading.Tasks.Task{GadzhiCommon.Models.Interfaces.Errors.IErrorConverting}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleError(System.Action,System.Action,System.Action,System.Action,System.String)~GadzhiCommon.Models.Interfaces.Errors.IErrorConverting")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Action,System.Action)~System.Threading.Tasks.Task{GadzhiCommon.Models.Interfaces.Errors.IResultConverting}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteBindErrors``1(System.Func{GadzhiCommon.Models.Interfaces.Errors.IResultConvertingValue{``0}})~GadzhiCommon.Models.Interfaces.Errors.IResultConverting")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteBindErrors``1(System.Func{GadzhiCommon.Models.Interfaces.Errors.IResultConvertingValue{``0}})~GadzhiCommon.Models.Interfaces.Errors.IResultConvertingValue{``0}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteBindErrors``2(System.Func{``0})~``0")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiConverting.Infrastructure.Implementations.ExecuteBindHandler.ExecuteBindFileDataErrors``1(System.Func{GadzhiCommon.Models.Interfaces.Errors.IResultConvertingValue{``0}},GadzhiCommon.Models.Interfaces.Errors.IErrorConverting)~GadzhiCommon.Models.Interfaces.Errors.IResultConvertingValue{``0}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiConverting.Infrastructure.Implementations.ExecuteBindHandler.ExecuteBindFileDataErrors``2(System.Func{``1},GadzhiCommon.Models.Interfaces.Errors.IErrorConverting)~``1")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiConverting.Infrastructure.Implementations.ExecuteBindHandler.ExecuteBindFileDataErrors``2(System.Func{``1},GadzhiCommon.Models.Interfaces.Errors.IErrorCommon)~``1")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleErrorAsync(System.Func{System.Threading.Tasks.Task},System.Action,System.Action,System.Action)~System.Threading.Tasks.Task{GadzhiCommon.Models.Interfaces.Errors.IResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiCommon.Infrastructure.Implementations.ExecuteAndCatchErrors.ExecuteAndHandleError(System.Action,System.Action,System.Action,System.Action,GadzhiCommon.Models.Interfaces.Errors.IErrorCommon)~GadzhiCommon.Models.Interfaces.Errors.IResult")]
