// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.FileDataEntity.FileDataSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.FileDataEntity.FileConvertErrorType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:GadzhiDAL.DependencyInjection.DependencyInjection.ConfigureContainer(Unity.IUnityContainer,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.PackageDataEntity.FilesData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.FileDataEntity.FileDataSourceEntity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.FileDataSourceEntity.FileDataSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Base.FileDataEntityBase.FileConvertErrorType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataEntity.FileDataSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataEntity.FileDataSourceEntity")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataSourceEntity.FileDataSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.PackageDataEntity.FilesData")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataEntity.FileConvertErrorType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataEntity.FileDataSource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:GadzhiDAL.Entities.FilesConvert.Main.FileDataEntity.FileDataSourceServerEntities")]